### ISSUE TITLE
When the docker package will be available

### ISSUE THREAD

**Issue by k0shk0sh** [danger/kotlin#124]
Thanks alot for the great lib, we finally migrated to it since a week now, I saw that https://github.com/danger/kotlin/pull/117 was merged, do you think we could have it in https://github.com/danger/kotlin/packages?package_type=Docker at time soon?

**Comment by f-meloni** [comment]
Hey @k0shk0sh 
Since we updated to kotlin 1.4.0 we are experiencing random failures like https://travis-ci.org/github/danger/kotlin/jobs/723180660 and we are investigating why.
We will try to fix it and if we can we will revert the change and release.
Also given yesterday GitHub announce (https://github.blog/2020-09-01-introducing-github-container-registry/) I think we will try to release the package directly on the container registry

**Comment by HeEAaD** [comment]
Thanks @f-meloni, we pulled the docker image with `uses: docker://ghcr.io/danger/danger-kotlin:0.7.0` in our Actions workflow. No Docker authentication was required. 👍

**Comment by f-meloni** [comment]
Great! 🎉🎉🎉

**Comment by f-meloni** [comment]
I'm closing this issue given is solved
