### ISSUE TITLE
Can't find Kotlin Compiler in Android Studio Preferences

### ISSUE THREAD

**Issue by JustJerem** [danger/kotlin#240]
Hi guys !
Thanks for this amazing version of Danger Kotlin, it's working fine on my side.
But I'm trying to make the auto-completion working and on[ this step](https://github.com/danger/kotlin#autocomplete-and-syntax-highlighting-in-intellij-idea-or-android-studio), I can't find **Kotlin Compiler** in Android Studio Preferences.

> Go to Preferences -> Build, Execution, Deployment -> Compiler -> Kotlin Compiler (Preferences -> Kotlin Compiler in Android Studio)

I normally installed Danger and restarted my IDE. I'm running on Android Studio Chipmunk | 2021.2.1 Patch 1.

![Screen Shot 2022-11-24 at 12 02 42](https://user-images.githubusercontent.com/13336422/203769925-38f65ebc-1673-4405-a779-df8833ddd180.png)

Did I miss anything?
Thanks you 🙏

**Comment by gianluz** [comment]
Try to close the project and open the settings without any project open but with the android studio initial screen. They have changed something, there you can find the option.

Also to make it working again try opening the danger file directly instead of the project, it will open the project initialising some stuff and then you will see the autocomplete working again

**Comment by gianluz** [comment]
let me know if that works for you!

**Comment by JustJerem** [comment]
Hi ! Thanks for the quick answer ! You're totally right, it's here ! Thanks again.

![Screen Shot 2022-11-24 at 16 48 35](https://user-images.githubusercontent.com/13336422/203824170-d490d951-d936-4813-b5ef-9968e16719bc.png)
