### ISSUE TITLE
Git.changedLines returns empty values for PullRequestChangedLines object

### ISSUE THREAD

**Issue by IvanSanchez-uam** [danger/kotlin#250]
I have these lines in my Danger.df.kts file

```
 warn("Additions = ${git.changedLines.additions}")
 warn("Deletions = ${git.changedLines.deletions}")
 warn("Diff = ${git.changedLines.diff ?: ""}")
```

in my case I want to get the diff but when calling `changedLines` extension function just give me 

Additions = 0
Deletions = 0
Diff = null

is this extension function really working?, is there another way to get the diff?

I also tried to use the github.pullRequest but there is no a diff value here.

I have the feeling that these lines are not working 

```
val Git.changedLines: PullRequestChangedLines
    get() {
        ...
        val commandRawOutput = shellExecutor.execute("git diff --numstat $headSha $baseSha")
        ...
        val commandRawDiffOutput = shellExecutor.execute("git diff $headSha $baseSha")
        return PullRequestChangedLines(additions, deletions, commandRawDiffOutput)
    }
```

**Comment by grine4ka** [comment]
So, I investigate a bit more and here what I came to.

The whole `git diff` was a bit... reverted. What do I mean?  
`git.changedLines.diff` didn't show anything because `baseSha` and `headSha` should be swapped.

To demonstrate current behaviour I've opened MR in my danger/kotlin fork: https://github.com/grine4ka/kotlin/pull/3.  
As you can see `git.changedLines.diff` shows additions and deletions reverted. Compare it with GitHub's `Files Changed` tab.

@IvanSanchez-uam BTW, if you use GitHub you should change `fetch-depth` to your checkout github action. Because by default it checks out a shallow clone with no history in it. So some commits are not visible on CI.
