### ISSUE TITLE
Integration with Danger in Ruby and Danger in JS

### ISSUE THREAD

**Issue by davidbilik** [danger/kotlin#67]
Hi, I'm new to Danger ecosystem, I am an Android developer and we use Danger in Ruby on our Jenkins/Gitlab to check our Merge requests. I've found this repository that is in Kotlin and I am curious if all plugins that I currently use in Ruby needs to write their version also in Kotlin or there is some option to use the ones in Ruby also in Kotlin. I'm not sure how this danger-kotlin works, if its a complete rewrite of Danger or its just a wrapper over the Ruby core so pardon if my question is silly. 

Thanks!

**Comment by orta** [comment]
You can't use the Ruby ones in Kotlin I'm afraid, but you're at the perfect time to start building ones you need because it's just got started

**Comment by gianluz** [comment]
Correct, more information regarding the plugin development is coming soon! Feel free to contact me directly for any needs

**Comment by davidbilik** [comment]
@gianluz ok, thanks. I will try to create some plugin tomorrow, I'm looking into the source codes of `danger-kotlin` and maybe it would help me if I create my plugin first as a dependency to the sourcode itself before using it through some dependency management system. Is it a good start to create new gradle module that depends on one of the exising modules (dont know which one currently) and inherit `DangerPlugin` class? I did not thought about how to run this local plugin and test it in DangerFile though.  If you want to move this discussion somewhere else I'm happy to, I'm on kotlinlang.slack for example :)

**Comment by gianluz** [comment]
the reference is the danger-kotlin-sdk for the plugin developement, you should be able to develop a simple plugin.. however there are some outstanding problems that i'm trying to solve:
- looks like since kotlin 1.3.61 is a bit changed how the dependencies are handled by the ivy resolver.
- a danger plugin needs to be tested with danger itself, this means we need to somehow link a local jar to the Dangerfile in a manner that makes us able to test the plugin locally and in CI.

I did few tests with my plugin here in this PR (master is not updated), that is the only one available at the moment:
https://github.com/gianluz/danger-kotlin-android-lint-plugin/pull/4

this will give you an idea. You can have a look in your free time, you can also contact me on the kotlinlang slack.. at the moment i'm quite active trying to understand how we can implement this for our Dangerscript. I'm happy to help you, and you can help me to make this done in order to release the 1.0.0 with documentation for the plugin developement 🎉 

My idea is also when the 1.0.0 will be released, publish in maven the sdk, and make simple the plugin development just using a maven dependency!

**Comment by gianluz** [comment]
closing this old issue
