### ISSUE TITLE
PRs from forks

### ISSUE THREAD

**Issue by Mkohm** [danger/kotlin#85]
Hi! 

Will PRs from forks work using danger/kotlin? I see that there is some problems with it with danger/ruby (https://github.com/danger/danger/issues/1103)

**Comment by f-meloni** [comment]
I don’t expect any problem with Danger itself.
We use Danger-Kotlin and we had PRs from forks e.g. https://github.com/danger/kotlin/pull/83
Sometimes the CI settings needs some additional changes in order to expose stuff like env variables and secrets to forks (where you have the token for Danger), if that is the case you will have to add those settings in order to be able to use Danger, if available.
If the default behaviour is not expose the secrets and there is no option to change it, unfortunately you won’t be able to run Danger on forks.

**Comment by orta** [comment]
That's on Danger Ruby which is a completely different implementation 👍
